// Free AI client — no login, no API key.
// Uses Pollinations.ai's public OpenAI-compatible endpoint, which proxies
// queries to a free model.
//
// Endpoint:  https://text.pollinations.ai/openai?referrer=<id>
// Auth:      none required (the ?referrer= query param identifies the caller
//            so Pollinations doesn't return their "deprecation" banner; ANY
//            string works — it's a soft self-identification, not auth)
// Cost:      free, rate-limited per IP
// Model:     'openai' (alias for openai-fast — GPT-OSS-20B reasoning LLM on
//            OVH, the only model on Pollinations' anonymous tier as of writing)
// Privacy:   queries pass through Pollinations; do not include secrets.

const ENDPOINT = 'https://text.pollinations.ai/openai';
const REFERRER = 'nkb-toolkit';

/**
 * Send a chat completion request to the free AI service.
 *
 * @param {Object} opts
 * @param {string} opts.prompt   - User question / instruction
 * @param {string} [opts.system] - Optional system prompt (role/persona)
 * @param {string} [opts.model]  - 'openai' (default), 'mistral', 'deepseek', etc.
 * @param {AbortSignal} [opts.signal]
 * @returns {Promise<string>} The assistant text content.
 */
export async function freeAi({ prompt, system, model = 'openai', signal } = {}) {
  if (!prompt || !prompt.trim()) throw new Error('prompt is required');
  const messages = [];
  if (system) messages.push({ role: 'system', content: system });
  messages.push({ role: 'user', content: prompt });

  const url = ENDPOINT + '?referrer=' + encodeURIComponent(REFERRER);
  const res = await fetch(url, {
    method: 'POST',
    mode: 'cors',
    headers: { 'Content-Type': 'application/json', 'Accept': 'application/json,text/plain' },
    body: JSON.stringify({ messages, model, stream: false, temperature: 0.2 }),
    signal
  });

  if (!res.ok) {
    const txt = await res.text().catch(() => '');
    throw new Error('AI request failed: HTTP ' + res.status + (txt ? ' — ' + txt.slice(0, 200) : ''));
  }

  const ct = res.headers.get('content-type') || '';
  let content;
  if (ct.includes('json')) {
    const j = await res.json();
    content = j?.choices?.[0]?.message?.content;
    if (typeof content !== 'string') content = JSON.stringify(j);
  } else {
    content = await res.text();
  }
  // Defensive: if the upstream is in a degraded mode and returns a service
  // banner instead of an AI response, surface a clear error rather than
  // showing the user a deprecation notice as their "regex" or "TCL script".
  if (/legacy text API is being deprecated|Pollinations legacy/i.test(content)) {
    throw new Error('Free AI endpoint is currently returning a service banner; please retry in a moment.');
  }
  return content;
}

/**
 * Mount a small status pill that can be toggled between idle / loading / error.
 */
export function setBusy(el, busy, label = 'Calling free AI…') {
  if (!el) return;
  if (busy) {
    el.textContent = label + ' ⌛';
    el.style.color = 'var(--text-3)';
  } else {
    el.textContent = '';
    el.style.color = '';
  }
}

/**
 * Strip code fences (```lang ... ```) from a response — many models
 * wrap their output in fences even when asked not to.
 */
export function stripFences(s) {
  if (!s) return s;
  const m = s.match(/```(?:\w+)?\s*\n?([\s\S]*?)\n?```/);
  return m ? m[1].trim() : s.trim();
}

/**
 * Brief credit line to display alongside any AI-generated output so users
 * understand provenance and can verify the result.
 */
export const AI_CREDIT = 'Generated by Pollinations.ai (free, no login). Always review before running.';
